#!/bin/bash

declare -A projects
projects=(
    ["cobalt-authorization"]="libs/hexworks/cobalt-authorization"
    ["cobalt-core"]="libs/hexworks/cobalt-core"
    ["cobalt-data"]="libs/hexworks/cobalt-data"
    ["cobalt-graphql"]="libs/hexworks/cobalt-graphql"
    ["cobalt-http"]="libs/hexworks/cobalt-http"
)

declare -A project_names
project_names=(
    ["authorization"]="cobalt-authorization"
    ["core"]="cobalt-core"
    ["events"]="cobalt-events"
    ["graphql"]="cobalt-graphql"
    ["http"]="cobalt-http"
    ["scheduler"]="cobalt-scheduler"
    ["state"]="cobalt-state"
)
