#!/bin/bash

cd "$(dirname "$0")"

source includes/projects

print_usage() {
    echo "💀 $1"
    echo "Help below 👇"
    echo ""
    echo "Publishes the given package. Will only work after performing a ./build-all."
    echo ""
    echo "Usage: ./publish <project>"
    ./projects
    exit 1
}

if [ -z "$1" ]; then
    print_usage "Project name is missing!"
fi

cd ../dist/libs/hexworks/${project_names[$1]}

npm publish --access public
